import { readFile } from 'node:fs/promises';
import { z } from 'zod';
import type { CapabilityHandler } from './capability-handler.js';

/**
 * application/gateway/models-catalog-handler: `list_models` (S3.11, docs/development-tasks.md
 * "中台控制面") — a read-only projection of the llm-proxy model whitelist. The kernel already
 * mounts the same `${NEXTTIME_DATA}/config` directory `worker-supervisor`/`agent-host` use to find
 * `models.json` (the compose kernel service's own volume: `${NEXTTIME_DATA:?}/config:
 * /data/config:ro` — no compose change needed for this task), generated by `packages/llm-proxy`'s
 * `gen-models-json` from `llm-providers.yaml` (`packages/worker-supervisor/src/host-paths.ts`'s
 * `hostConfigModelsJsonPath` names the same `${NEXTTIME_DATA}/config/models.json` path).
 *
 * Deliberately re-declares only the `providers.<name>.models[].id` shape locally rather than
 * importing `@nexttime/llm-proxy`'s own `PiModelsJson` type — the kernel does not depend on that
 * package, and this handler only ever needs one field per model. `apiKey`/`baseUrl`/`api`/`cost`
 * never reach this schema, let alone the wire: `models.json`'s own `apiKey` field is always the
 * literal template string `$CAPABILITY_HANDLE`, never a real provider key
 * (`gen-models-json.ts`'s own doc comment), but this handler does not even parse that field, so
 * the kernel process never sees anything provider-credential-shaped even in principle.
 */

const DEFAULT_MODELS_JSON_FILE = '/data/config/models.json';

function resolveModelsJsonFile(env: NodeJS.ProcessEnv): string {
  const configured = env.MODELS_JSON_FILE;
  return configured && configured.length > 0 ? configured : DEFAULT_MODELS_JSON_FILE;
}

const ModelsJsonSchema = z.object({
  providers: z.record(
    z.string(),
    z
      .object({
        models: z.array(z.object({ id: z.string().min(1) }).passthrough()),
      })
      .passthrough(),
  ),
});

/**
 * Thrown when `models.json` is missing, unreadable, or does not match the expected shape —
 * mapped to HTTP 503 / WS SERVICE_UNAVAILABLE (interfaces/http/capability-route.ts, interfaces/ws/
 * rpc.ts), the same "the kernel process itself is not ready to serve this capability yet" bucket
 * `TaskRuntimeNotConfiguredError` already uses (application/task/runtime.ts) — not a caller-input
 * problem (400/404/409 all wrong), and not silently a caller-invisible internal bug either.
 */
export class ModelsCatalogUnavailableError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = 'ModelsCatalogUnavailableError';
  }
}

export interface ModelCatalogEntry {
  readonly id: string;
  readonly provider: string;
  readonly model: string;
}

/**
 * Reads and parses `models.json`, projecting every provider's model list to `{id, provider,
 * model}` — `id` is `<provider>/<model>`, the same `provider/id` shape a WorkerDefinition's own
 * `model` field and S3.13's future `AgentProfile.model` already use (docs/development-tasks.md
 * S3.13: "model（provider/id，必须 ∈ llm-proxy 白名单）"). Exported (not only the wired handler
 * below) so that future validation can reuse this same read without a second models.json parser.
 */
export async function readModelCatalog(
  env: NodeJS.ProcessEnv = process.env,
): Promise<readonly ModelCatalogEntry[]> {
  const file = resolveModelsJsonFile(env);

  let raw: string;
  try {
    raw = await readFile(file, 'utf8');
  } catch (err) {
    throw new ModelsCatalogUnavailableError(
      `list_models: could not read models.json at "${file}"`,
      { cause: err },
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new ModelsCatalogUnavailableError(`list_models: "${file}" is not valid JSON`, {
      cause: err,
    });
  }

  const result = ModelsJsonSchema.safeParse(parsed);
  if (!result.success) {
    throw new ModelsCatalogUnavailableError(
      `list_models: "${file}" does not match the expected models.json shape`,
      { cause: result.error },
    );
  }

  const items: ModelCatalogEntry[] = [];
  for (const [provider, providerConfig] of Object.entries(result.data.providers)) {
    for (const model of providerConfig.models) {
      items.push({ id: `${provider}/${model.id}`, provider, model: model.id });
    }
  }
  return items;
}

export const listModelsHandler: CapabilityHandler = async () => {
  const items = await readModelCatalog();
  return { result: { items } };
};
