#!/bin/sh
# host-env-init.sh — create NextTime-AI's runtime secrets/config placeholders under
# $NEXTTIME_DATA and fix directory ownership so the platform's non-root containers can use
# their mounts. POSIX sh, idempotent. See docs/development-tasks.md E3/E4 and
# docs/graph-ai-middle-platform-design.md §10.2.
#
# Usage (local):
#   NEXTTIME_DATA=/path/to/data sh scripts/host-env-init.sh
#
# Usage (remote, piped over SSH):
#   ssh <TARGET_HOST> 'NEXTTIME_DATA=/path/to/data sh -s' < scripts/host-env-init.sh
#
# Requires: $NEXTTIME_DATA already bootstrapped by scripts/host-bootstrap.sh (task E2) — this
# script does not create the top-level directory tree, only files inside it plus an ownership
# fix-up on a few of those directories.
#
# Scope: writes secrets/{kernel,llm-proxy,gatekeeper-ragflow}.env and
# config/{llm-providers.yaml,models.json,handle.pub,egress-sources.json} as placeholders/
# templates — no real credentials exist yet at this point in the task list (S1.7/S1.9/S3.4 fill
# them in later; egress-sources.json is S1.11's SOURCE_MAP_FILE for egress-proxy, design doc
# §7.9 — an empty object is a valid "no sources registered yet" map, not a stub for a later
# task to overwrite).
# Then chowns sessions/ workspaces/ artifacts/ caddy/ to the non-root uid:gid the platform's
# containers run as, and makes config/ world-readable (it holds no secrets). Never echoes
# secret file contents. Touches nothing outside $NEXTTIME_DATA.

set -eu

# --- guard: NEXTTIME_DATA must be set, must not be "/", and must already be bootstrapped -----
if [ -z "${NEXTTIME_DATA:-}" ]; then
	echo "host-env-init: NEXTTIME_DATA is not set; refusing to run" >&2
	exit 1
fi

if [ "$NEXTTIME_DATA" = "/" ]; then
	echo "host-env-init: NEXTTIME_DATA is '/'; refusing to run" >&2
	exit 1
fi

SECRETS_DIR="$NEXTTIME_DATA/secrets"
CONFIG_DIR="$NEXTTIME_DATA/config"
PG_PASSWORD_FILE="$SECRETS_DIR/pg_password"

if [ ! -d "$SECRETS_DIR" ] || [ ! -d "$CONFIG_DIR" ]; then
	echo "host-env-init: $NEXTTIME_DATA is missing secrets/ or config/ — run scripts/host-bootstrap.sh (E2) first" >&2
	exit 1
fi

if [ ! -s "$PG_PASSWORD_FILE" ]; then
	echo "host-env-init: $PG_PASSWORD_FILE missing or empty — run scripts/host-bootstrap.sh (E2) first" >&2
	exit 1
fi

echo "host-env-init: target NEXTTIME_DATA=$NEXTTIME_DATA"

# --- non-root uid:gid the platform's containers run as ---------------------------------------
# All five packages/*/Dockerfile (kernel, agent-host, worker-supervisor, llm-proxy,
# egress-proxy) create the same system user/group: `nexttime`, uid 10001, gid 10001
# (`groupadd --system --gid 10001 nexttime` + `useradd --system --uid 10001 --gid nexttime`).
# Keep these two constants in sync with those Dockerfiles if that ever changes.
CONTAINER_UID=10001
CONTAINER_GID=10001

# --- urlencode: percent-encode everything outside RFC 3986 unreserved [A-Za-z0-9.~_-] --------
# POSIX-only (no bash-isms): `${s%"${s#?}"}` takes the first character of $s, `${s#?}` strips
# it. `printf '%%%02X' "'$c"` relies on POSIX printf's rule that a numeric conversion given an
# argument starting with `'` takes the numeric value of the following character.
urlencode() {
	s=$1
	out=""
	while [ -n "$s" ]; do
		c=${s%"${s#?}"}
		case "$c" in
			[A-Za-z0-9.~_-]) out="$out$c" ;;
			*) out="$out$(printf '%%%02X' "'$c")" ;;
		esac
		s=${s#?}
	done
	printf '%s' "$out"
}

CREATED=""
SKIPPED=""

# --- secrets/kernel.env: DATABASE_URL (from secrets/pg_password) + Handle key placeholder -----
KERNEL_ENV="$SECRETS_DIR/kernel.env"
if [ ! -s "$KERNEL_ENV" ]; then
	pg_password=$(cat "$PG_PASSWORD_FILE")
	encoded_password=$(urlencode "$pg_password")
	{
		echo "# kernel.env — generated by scripts/host-env-init.sh. Real secret; never commit."
		echo "DATABASE_URL=postgres://nexttime:${encoded_password}@postgres:5432/nexttime"
		echo "# Placeholder: S1.9 generates the real Handle signing keypair and writes the"
		echo "# private key at this path; the kernel process reads it from here."
		echo "HANDLE_PRIVATE_KEY_FILE=/data/config/handle.key"
	} >"$KERNEL_ENV"
	unset pg_password encoded_password
	CREATED="$CREATED secrets/kernel.env"
else
	SKIPPED="$SKIPPED secrets/kernel.env"
fi
chmod 600 "$KERNEL_ENV"

# --- secrets/llm-proxy.env: commented template, no values (S1.7 defines the real key names) ---
LLM_PROXY_ENV="$SECRETS_DIR/llm-proxy.env"
if [ ! -f "$LLM_PROXY_ENV" ]; then
	cat >"$LLM_PROXY_ENV" <<'EOF'
# llm-proxy secrets template (design doc §7.7). Real provider API keys go here — never commit.
# S1.7 (packages/llm-proxy) defines the exact key names read from this file; each must match the
# `key_env` referenced by the corresponding provider entry in config/llm-providers.yaml.
#
# Example (uncomment and fill in when connecting a real provider):
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
EOF
	CREATED="$CREATED secrets/llm-proxy.env"
else
	SKIPPED="$SKIPPED secrets/llm-proxy.env"
fi
chmod 600 "$LLM_PROXY_ENV"

# --- secrets/gatekeeper-ragflow.env: commented template, no values (S3.4 defines the shape) ---
RAGFLOW_ENV="$SECRETS_DIR/gatekeeper-ragflow.env"
if [ ! -f "$RAGFLOW_ENV" ]; then
	cat >"$RAGFLOW_ENV" <<'EOF'
# gatekeeper-ragflow secrets template (design doc §7.5; task S3.4). Real RAGFlow URL/API key for
# this gatekeeper instance go here — never commit. The platform keeps its own copy; it does not
# share a credentials file with any other RAGFlow client on this host.
#
# Example (uncomment and fill in when connecting):
# RAGFLOW_URL=
# RAGFLOW_API_KEY=
EOF
	CREATED="$CREATED secrets/gatekeeper-ragflow.env"
else
	SKIPPED="$SKIPPED secrets/gatekeeper-ragflow.env"
fi
chmod 600 "$RAGFLOW_ENV"

# --- config/llm-providers.yaml: draft shape per design §7.5/§7.7, no keys ---------------------
LLM_PROVIDERS_YAML="$CONFIG_DIR/llm-providers.yaml"
if [ ! -f "$LLM_PROVIDERS_YAML" ]; then
	cat >"$LLM_PROVIDERS_YAML" <<'EOF'
# Placeholder — no real provider endpoints or keys here. S1.7 (packages/llm-proxy) defines the
# authoritative shape this file must have; scripts/gen-models-json.ts (S1.7) then derives
# config/models.json and the kernel's route table from it. See design doc §7.5, §7.7.
providers: []
# Example provider entry (commented draft — uncomment and adapt once S1.7 lands):
# providers:
#   - id: example-provider
#     base_url: https://api.example.invalid/v1
#     auth:
#       header: Authorization
#       value_prefix: "Bearer "
#       key_env: EXAMPLE_PROVIDER_API_KEY   # name of a key in secrets/llm-proxy.env
#     models:
#       - id: example-model-id
#         alias: example-alias
EOF
	CREATED="$CREATED config/llm-providers.yaml"
else
	SKIPPED="$SKIPPED config/llm-providers.yaml"
fi

# --- config/models.json: empty object; S1.7's gen-models-json.ts regenerates it ---------------
MODELS_JSON="$CONFIG_DIR/models.json"
if [ ! -f "$MODELS_JSON" ]; then
	echo "{}" >"$MODELS_JSON"
	CREATED="$CREATED config/models.json"
else
	SKIPPED="$SKIPPED config/models.json"
fi

# --- config/handle.pub: empty placeholder; S1.9 writes the real Handle-signing public key -----
HANDLE_PUB="$CONFIG_DIR/handle.pub"
if [ ! -f "$HANDLE_PUB" ]; then
	: >"$HANDLE_PUB"
	CREATED="$CREATED config/handle.pub"
else
	SKIPPED="$SKIPPED config/handle.pub"
fi

# --- config/egress-sources.json: empty object; docker-compose.yml bind-mounts this file -------
# read-only into egress-proxy (SOURCE_MAP_FILE) — if missing, Docker would create a directory
# at that path instead of a file.
EGRESS_SOURCES_JSON="$CONFIG_DIR/egress-sources.json"
if [ ! -f "$EGRESS_SOURCES_JSON" ]; then
	echo "{}" >"$EGRESS_SOURCES_JSON"
	CREATED="$CREATED config/egress-sources.json"
else
	SKIPPED="$SKIPPED config/egress-sources.json"
fi

# --- ownership: sessions/ workspaces/ artifacts/ caddy/ must be usable by the platform's ------
# non-root containers (uid:gid 10001:10001). pgdata/ (the postgres image manages its own
# ownership), secrets/ (root-owned, 0700 — compose passes its contents via env_file / Docker
# secrets, not a bind-mounted directory read by a container process) and backups/ are left
# untouched, per task scope.
for d in sessions workspaces artifacts caddy; do
	chown -R "${CONTAINER_UID}:${CONTAINER_GID}" "$NEXTTIME_DATA/$d"
done

# --- config/: left root-owned but made world-readable (it holds no secrets — provider keys ----
# live in secrets/*.env instead) so any container uid can read it read-only.
chmod 755 "$CONFIG_DIR"
for f in "$CONFIG_DIR"/*; do
	[ -f "$f" ] && chmod 644 "$f"
done

# --- report -------------------------------------------------------------------------------
echo ""
echo "host-env-init: created:${CREATED:- (none — all already existed)}"
echo "host-env-init: already existed, left unchanged:${SKIPPED:- (none)}"
echo ""
echo "host-env-init: secrets/*.env (mode, path):"
for f in kernel.env llm-proxy.env gatekeeper-ragflow.env; do
	echo "  $(stat -c '%a' "$SECRETS_DIR/$f" 2>/dev/null || echo '?') $SECRETS_DIR/$f"
done
echo ""
echo "host-env-init: config/ (mode, owner:group, path):"
find "$CONFIG_DIR" -maxdepth 1 -printf '  %M %U:%G %p\n'
echo ""
echo "host-env-init: ownership fix-up (uid:gid ${CONTAINER_UID}:${CONTAINER_GID}) applied to:"
for d in sessions workspaces artifacts caddy; do
	echo "  $NEXTTIME_DATA/$d -> $(stat -c '%U:%G' "$NEXTTIME_DATA/$d")"
done
echo ""
echo "host-env-init: left untouched: pgdata/ secrets/ (dir itself) backups/"
echo "host-env-init: done (idempotent — safe to re-run)"
